apiVersion: v1
kind: Namespace
metadata:
  name: risalah-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: risalah-ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: risalah-data
---
apiVersion: v1
kind: Namespace
metadata:
  name: risalah-infra
