apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: risalah-app

resources:
  - ../../app/deployment.yaml
  - ../../ai
  - ../../data
  - ../../infra

patches:
  - path: staging-patch.yaml
